version: '3'

vars:
  APP_NAME: "mercury"
  BIN_DIR: "bin"
  PACKAGE_MANAGER: '{{.PACKAGE_MANAGER | default "bun"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  GOOS: '{{.GOOS | default OS}}'

includes:
  common: ./build/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  windows: ./build/windows/Taskfile.yml

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{.GOOS}}:build"

  run:
    summary: Runs the application
    cmds:
      - task: "{{.GOOS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
