name: Deploy docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install deps
        run: bun install
      - name: Build
        run: bun run build
      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          GIT_USER=striker561 GIT_PASS=${{ secrets.GITHUB_TOKEN }} bun run deploy
